Model (
	Req (" liveStream ") ,
	Req (" commentsSection ") ,
	Req (" lectureRating ") ,
	Req (" liveStreamQuestion ") ,
	Req (" playVideo ") ,
	Req (" courseRating ") ,
	Req (" lectureSlides ") ,
	Req (" stilLogin ") ,
	Req (" lucatLogin ") ,
	Req (" liveStreamChat ") ,
	Req (" courseInfo ") ,
	Req (" coursePage ") ,
	Req (" courseRatingDisplay ") ,
	Req (" lectureRatingDisplay ") ,
	Req (" adminLogin ") ,
	Stakeholder (" lecturer ") ,
	Stakeholder (" student ") )